### ISSUE TITLE
Support default and optional ConfigMap values

### ISSUE THREAD

**Issue by gordon-rennie** [ovotech/ciris-kubernetes#21]
Firstly, thanks for the library!

`ciris` supports optional and default values (see e.g. [`ConfigValue#option`,](https://github.com/vlovgr/ciris/blob/e57dbb8f46321564cb0b0333998e89e076b0cc34/modules/core/src/main/scala/ciris/ConfigValue.scala#L180)) which returns an empty, or a specified default value, if a ConfigValue contains an error with [`error.isMissing = true`](https://github.com/vlovgr/ciris/blob/e57dbb8f46321564cb0b0333998e89e076b0cc34/modules/core/src/main/scala/ciris/ConfigError.scala).

It is not possible to use this functionality in `ciris-kubernetes` for values inside a `ConfigMap`, because if no value is found for the key then a generic `ConfigError.failed` is returned instead of a `ConfigError.missing`. Calls to `.option` will not recover from the error to an empty value. 

The relevant code here:
https://github.com/ovotech/ciris-kubernetes/blob/bba154fad2d3474540ce6199c3305b94ca4deff9/src/main/scala/ciris/kubernetes.scala#L71-L90

I have a use case where I'd like to have an optional config param inside a configmap. If this isn't objectionable, the fix seems pretty straight forward and I'm happy to put in the PR to change to return a `ConfigError.missing` here:
https://github.com/ovotech/ciris-kubernetes/blob/bba154fad2d3474540ce6199c3305b94ca4deff9/src/main/scala/ciris/kubernetes.scala#L84-L88

**Comment by vlovgr** [comment]
Sounds good to me @gordon-rennie! I also think we should have a `case None if entries.size == 0` which returns `ConfigValue.missing`.
